# Generated by Django 5.2.9 on 2025-12-16 13:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeData',
            fields=[
                ('receipe_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('receipe_name', models.CharField(max_length=150)),
                ('receipe_description', models.TextField()),
                ('rating', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='image/')),
            ],
        ),
    ]
