# Generated by Django 5.2.9 on 2025-12-16 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipedata',
            old_name='receipe_description',
            new_name='recipe_description',
        ),
        migrations.RenameField(
            model_name='recipedata',
            old_name='receipe_id',
            new_name='recipe_id',
        ),
        migrations.RenameField(
            model_name='recipedata',
            old_name='receipe_name',
            new_name='recipe_name',
        ),
    ]
